///* DO NOT EDIT THIS FILE - it is machine generated */
//#include <jni.h>
//#include <string>
//#include <pthread.h>
///* Header for class yueshao_com_jniapplication_NativeMethod */
//
//#ifndef _Included_yueshao_com_jniapplication_NativeMethod
//#define _Included_yueshao_com_jniapplication_NativeMethod
//#ifdef __cplusplus
//extern "C" {
//#endif
///*
// * Class:     yueshao_com_jniapplication_NativeMethod
// * Method:    getAesKey
// * Signature: ()Ljava/lang/String;
// */
//JNIEXPORT jstring JNICALL Java_yueshao_com_jniapplication_NativeMethod_getAesKey
//  (JNIEnv *, jobject);
//
///*
// * Class:     yueshao_com_jniapplication_NativeMethod
// * Method:    CallBackJni
// * Signature: (Lyueshao/com/jniapplication/CallBackJni;)V
// */
//JNIEXPORT void JNICALL Java_yueshao_com_jniapplication_NativeMethod_CallBack
//  (JNIEnv *, jobject, jobject);
//
//#ifdef __cplusplus
//}
//#endif
//#endif
